<div style="text-align: center;">
   <font size="5"> 線形代数(Linear Algebra III) ベクトル空間 </font>
</div>
   <div style="text-align: right;">
   <font size="3"> cc by Shigeto R. Nishitani, 2018-03-16 </font>
</div>

* file: /Users/bob/python/doing_math_with_python/linear_algebra/LA-III_vector_space.ipynb

# Table of Contents
 <p><div class="lev1 toc-item"><a href="#ベクトル空間" data-toc-modified-id="ベクトル空間-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>ベクトル空間</a></div><div class="lev1 toc-item"><a href="#行列式" data-toc-modified-id="行列式-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>行列式</a></div><div class="lev1 toc-item"><a href="#ベクトル空間" data-toc-modified-id="ベクトル空間-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>ベクトル空間</a></div>

# ベクトル空間

* **実数上の$n$次(元)数ベクトル空間**
実数の$n$個の組の全体
$$
\boldsymbol{R}^n = \{ (a_1,a_2,\ldots,a_n); a_1, a_2, \ldots, a_n \in \boldsymbol{R} \}
$$

* **基底，次元，成分**

* **部分空間**
   * 数ベクトル空間$\boldsymbol{R}^n$の部分集合$V(\neq 0)$が和とスカラー倍に閉じているとき，$\boldsymbol{R}^n$の**部分空間**という．

   * **同次連立一次方程式の解空間**:$A$を$m \times n$行列とする．
同次連立一次方程式$A\boldsymbol{x} = \boldsymbol{0}$の解全体
$\{\boldsymbol{x} \in \boldsymbol{R}^n; A\boldsymbol{x} = \boldsymbol{0}\}$
は$ \boldsymbol{R}^n$の部分空間をなす．
これを$A\boldsymbol{x} = \boldsymbol{0}$の解空間という．
$$
{\rm dim}\{\boldsymbol{x} \in \boldsymbol{R}^n; A\boldsymbol{x} = \boldsymbol{0}\}
= n -{\rm rank}A
$$
であり，基本解は1組の基底である．

* 計量ベクトル空間
  * 内積を考えているとき$V$を計量ベクトル空間または内積空間という．

* 直交基底
   * グラム・シュミットの直交化法

* 直交補空間



# ベクトル空間

![LA-II](./figs/LinearAlgebra-III.png)


In [3]:
import numpy as np
from pprint import pprint
import scipy.linalg as linalg

np.set_printoptions(precision=3, suppress=True)

a = np.array([[1,2],[3,4]])
linalg.det(a)

-2.0

In [4]:
linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [9]:
a = np.array([[1,-2,3],[2,-3,4],[3,-8,13]])
pprint(linalg.det(a))
pprint(linalg.inv(a))

-9.62193288008469e-16
array([[  1.892e+16,  -5.404e+15,  -2.702e+15],
       [  3.783e+16,  -1.081e+16,  -5.404e+15],
       [  1.892e+16,  -5.404e+15,  -2.702e+15]])


In [10]:
a = np.array([[1,2,-1],[-1,-1,2],[2,-1,1]])
pprint(linalg.det(a))
pprint(linalg.inv(a))

8.0
array([[ 0.125, -0.125,  0.375],
       [ 0.625,  0.375, -0.125],
       [ 0.375,  0.625,  0.125]])
