In [2]:
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.3f}'.format}) 


A = np.array([[4,5,5],[-4,-5,-7],[4,4,6]])
l, P = np.linalg.eig( A )
print(l)
print(P)

[ 4.000  2.000 -1.000]
[[-0.333  0.000 -0.707]
 [ 0.667  0.707  0.707]
 [-0.667 -0.707  0.000]]


In [3]:
from pprint import pprint
dA = np.dot(np.linalg.inv(P),np.dot(A,P))
np.set_printoptions(precision=3, suppress=True)
print(format(dA))

[[ 4. -0.  0.]
 [ 0.  2. -0.]
 [ 0.  0. -1.]]
